# This file contains necessary configuration for the coordinator web app

name: app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  sizer: ^2.0.15
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.0

  flutter_web_plugins:
    sdk: flutter
  file_picker: ^6.1.1
  dio: ^5.4.0
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  simplify: ^1.0.2
  gpx: ^2.2.1
  latlong2: ^0.9.0
  date_field: ^3.0.5
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  provider: ^6.1.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - res/

